export const Actions = {
	UPDATE_TICKET_STATE: "UPDATE_COLLAB_STATE",
	RESET_STATE: "RESET_STATE",
	FETCH_TICKET_DETAILS: "FETCH_TICKET_DETAILS",
	FETCH_MORE_TICKET_DETAILS: "FETCH_MORE_TICKET_DETAILS",
};
